import {
  BriefcaseBusiness,
  CarFront,
  HeartPulse,
  PiggyBank,
  ShoppingCart,
  Ticket,
  ToolCase,
  Utensils,
  PawPrint,
  House,
  Gift,
  Dumbbell,
  BookOpen,
  BaggageClaim,
  Mailbox,
  ReceiptText,
} from 'lucide-angular';

export const CATEGORY_ICONS = {
  briefcasebusiness: BriefcaseBusiness,
  carfront: CarFront,
  heartpulse: HeartPulse,
  piggybank: PiggyBank,
  shoppingcart: ShoppingCart,
  ticket: Ticket,
  toolcase: ToolCase,
  utensils: Utensils,
  pawprint: PawPrint,
  house: House,
  gift: Gift,
  dumbbell: Dumbbell,
  bookopen: BookOpen,
  baggageclaim: BaggageClaim,
  mailbox: Mailbox,
  receipttext: ReceiptText,
};
