spring.application.name=financy

spring.datasource.url=jdbc:postgresql://ep-plain-rain-ac5txbth-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5d2IluMVeRax

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true